### ISSUE TITLE
raw data?

### ISSUE THREAD

**Issue by JieyuZ2** [autonlab/weasel#1]
Hi,

Great work! Just wondering if the raw data, eg, raw text for IMDb and Amazon could be also released?

**Comment by salvaRC** [comment]
Thank you!
For this project we only created new LF sets at most.
The used data features all follow prior work:
Raw text data for IMDB, Amazon, and BiasBios are used in the processed form of "Interactive Weak Supervision: Learning Useful Heuristics for Data Labeling" (https://arxiv.org/abs/2012.06046). But the raw data for, eg, IMDB should be accessible here: https://ai.stanford.edu/~amaas/data/sentiment/
