### ISSUE TITLE
Request for Labeling Functions

### ISSUE THREAD

**Issue by yongzx** [autonlab/weasel#2]
Thanks for open-sourcing the code! Quick question: where can I find the additional labeling functions for Amazon, IMDB (136 LFs), and BiasBios (99 LFs)?

**Comment by salvaRC** [comment]
Hi :), you can switch to the 'research_code' branch. There you'll find all that info -- most relevant: "The smallest dataset, Bias in Bios is already included in the data subdirectory. All the rest can be downloaded from this Google drive link. Please put the downloaded data into the data/ directory."

**Comment by salvaRC** [comment]
where the gdrive link is https://drive.google.com/drive/folders/1v7IzA3Ab5zDEsRpLBWmJnXo5841tSOlh?usp=sharing

**Comment by yongzx** [comment]
Hi @salvaRC, thanks for the prompt reply! Quick follow-up on the Drive: I couldn't find the labeling function codes other than the existing label votes. Am I missing something?

**Comment by salvaRC** [comment]
Ahh, now I understand -- good point @yongzx !
We hadn't uploaded any LF definitions, indeed.

In the research_code branch I just uploaded in the data subdir the files lfs_to_use_<dataset>.txt which contain all the used LF definitions (simple keyword detectors).
The instructions for arriving at the label matrices that we uploaded are described in the updates to the following readme:
https://github.com/autonlab/weasel/blob/research_code/data/README.md 

I hope that helps & let me know if anything is unclear :)
