### ISSUE TITLE
Multi-Label

### ISSUE THREAD

**Issue by hanshupe** [autonlab/weasel#6]
Is there anything to consider for multi-labelling problems?

**Comment by salvaRC** [comment]
Weasel was not designed or evaluated on this setting. It would probably be possible to adapt it to it though. For example, right now the encoder model assumes that each LF labels for one class or abstains. If there are LFs that label multiple classes, this needs to be adapted, e.g. by using the one-hot label matrix (which for multilabel classification of course might not be one-hot any more).
Let us know if your get it to work successfully! :)
