### ISSUE TITLE
Errors in example scripts and notebook

### ISSUE THREAD

**Issue by vidyasujaya** [autonlab/weasel#7]
Hello, thank you for sharing this work! I've been trying to run the example scripts and notebooks before running weasel on a different dataset. I keep on coming across the following exceptions when trying to fit weasel and the end-model: 

1. TypeError in 0_full_pipeline.ipynb
> TypeError: vars() argument must have __dict__ attribute

2. MisconfigurationException in all other files in the examples folder
> lightning_fabric.utilities.exceptions.MisconfigurationException: You are trying to `self.log()` but it is not managed by the `Trainer` control flow

Do you know what might be the problem?

**Comment by salvaRC** [comment]
Hello! At least with regard to the 2nd problem, it should be fixed now with the latest update to the code base. I'm not sure about the first error, but let me know if there are any other questions :)
